import type { FinanceStore } from '@/types/finance';

const ts = '2025-01-01T00:00:00.000Z';

const FLAT_ID = 'seed-asset-flat';
const ETF_ID = 'seed-asset-etf';
const CASH_ID = 'seed-asset-cash';
const CRYPTO_ID = 'seed-asset-crypto';
const CAR_ID = 'seed-asset-car';
const MORTGAGE_ID = 'seed-loan-mortgage';
const PERSONAL_LOAN_ID = 'seed-loan-personal';
const FLAT_TAX_ID = 'seed-recurring-flat-tax';
const RENT_INCOME_ID = 'seed-income-rent';
const DIVIDEND_INCOME_ID = 'seed-income-dividends';

export const SEED_STORE: FinanceStore = {
  currency: 'CZK',
  assets: [
    {
      id: FLAT_ID,
      name: 'Prague Apartment',
      type: 'real_estate',
      value: 6_500_000,
      currency: 'CZK',
      yearlyGrowthRate: 0.03,
      usage: 'leasing',
      rentSavings: null,
      linkedIncomeIds: [RENT_INCOME_ID],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: ETF_ID,
      name: 'Vanguard FTSE All-World',
      type: 'etf',
      value: 1_200_000,
      currency: 'CZK',
      yearlyGrowthRate: 0.07,
      usage: null,
      rentSavings: null,
      linkedIncomeIds: [DIVIDEND_INCOME_ID],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: CASH_ID,
      name: 'Emergency Fund',
      type: 'cash',
      value: 350_000,
      currency: 'CZK',
      yearlyGrowthRate: 0.02,
      usage: null,
      rentSavings: null,
      linkedIncomeIds: [],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: CRYPTO_ID,
      name: 'Bitcoin',
      type: 'crypto',
      value: 180_000,
      currency: 'CZK',
      yearlyGrowthRate: 0.1,
      usage: null,
      rentSavings: null,
      linkedIncomeIds: [],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: CAR_ID,
      name: 'Car',
      type: 'other',
      value: 300_000,
      currency: 'CZK',
      yearlyGrowthRate: -0.1,
      usage: null,
      rentSavings: null,
      linkedIncomeIds: [],
      createdAt: ts,
      updatedAt: ts,
    },
  ],
  liabilities: [
    {
      id: MORTGAGE_ID,
      type: 'loan',
      name: 'Apartment Mortgage',
      loanType: 'living_mortgage',
      originalAmount: 5_000_000,
      currentBalance: 4_200_000,
      interestRate: 0.049,
      monthlyPayment: 26_500,
      startDate: '2022-03-01',
      endDate: '2047-03-01',
      linkedAssetId: FLAT_ID,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: PERSONAL_LOAN_ID,
      type: 'loan',
      name: 'Car Loan',
      loanType: 'personal',
      originalAmount: 400_000,
      currentBalance: 220_000,
      interestRate: 0.069,
      monthlyPayment: 7_800,
      startDate: '2023-06-01',
      endDate: '2028-06-01',
      linkedAssetId: CAR_ID,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: FLAT_TAX_ID,
      type: 'recurring',
      name: 'Apartment Property Tax',
      amount: 1_200,
      frequency: 'annually',
      currency: 'CZK',
      linkedAssetId: FLAT_ID,
      createdAt: ts,
      updatedAt: ts,
    },
  ],
  incomes: [
    {
      id: 'seed-income-salary',
      name: 'Software Engineer Salary',
      type: 'salary',
      amount: 95_000,
      frequency: 'monthly',
      isPassive: false,
      currency: 'CZK',
      linkedAssetId: null,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: RENT_INCOME_ID,
      name: 'Apartment Rent',
      type: 'rental',
      amount: 22_000,
      frequency: 'monthly',
      isPassive: true,
      currency: 'CZK',
      linkedAssetId: FLAT_ID,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: DIVIDEND_INCOME_ID,
      name: 'ETF Dividends',
      type: 'dividends',
      amount: 4_800,
      frequency: 'quarterly',
      isPassive: true,
      currency: 'CZK',
      linkedAssetId: ETF_ID,
      createdAt: ts,
      updatedAt: ts,
    },
  ],
  expenses: [
    {
      id: 'seed-expense-housing',
      name: 'Rent + Utilities',
      category: 'living_expense',
      amount: 18_000,
      frequency: 'monthly',
      isEssential: true,
      currency: 'CZK',
      linkedLiabilityId: null,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: 'seed-expense-food',
      name: 'Groceries & Dining',
      category: 'living_expense',
      amount: 12_000,
      frequency: 'monthly',
      isEssential: true,
      currency: 'CZK',
      linkedLiabilityId: null,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: 'seed-expense-transport',
      name: 'Transport',
      category: 'living_expense',
      amount: 4_000,
      frequency: 'monthly',
      isEssential: false,
      currency: 'CZK',
      linkedLiabilityId: null,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: 'seed-expense-misc',
      name: 'Entertainment & Misc',
      category: 'living_expense',
      amount: 8_000,
      frequency: 'monthly',
      isEssential: false,
      currency: 'CZK',
      linkedLiabilityId: null,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: 'seed-expense-mortgage',
      name: 'Mortgage Payment',
      category: 'liability',
      amount: 26_500,
      frequency: 'monthly',
      isEssential: true,
      currency: 'CZK',
      linkedLiabilityId: MORTGAGE_ID,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: 'seed-expense-carloan',
      name: 'Car Loan Payment',
      category: 'liability',
      amount: 7_800,
      frequency: 'monthly',
      isEssential: true,
      currency: 'CZK',
      linkedLiabilityId: PERSONAL_LOAN_ID,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: 'seed-expense-flat-tax',
      name: 'Apartment Property Tax',
      category: 'ownership',
      amount: 1_200,
      frequency: 'annually',
      isEssential: true,
      currency: 'CZK',
      linkedLiabilityId: FLAT_TAX_ID,
      createdAt: ts,
      updatedAt: ts,
    },
  ],
};
